# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c4047ee89f36915ccb22809fe8d2679aeab0dbc5c9ec3227c86bbbcbe8c6c61215e8d2ee1679c1552124a3b92cd561e2a8122d58f9d1a0da932ef70cf9ab68

test:
  secret_key_base: 04362a13cb262dce330c687284619344a179edca21d08f188bfff6bae4ec295245854a86808870e664a7ee94725f0d68dbba71a0ddf759e8065640c5a91df388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
